package com.example.dbutil;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table topic.
 */
public class TopicItem {

    private Boolean saved;
    private String topicId;
    private String topicName;
    private String topicImage;
    private String latter;

    public TopicItem() {
    }

    public TopicItem(Boolean saved, String topicId, String topicName, String topicImage, String latter) {
        this.saved = saved;
        this.topicId = topicId;
        this.topicName = topicName;
        this.topicImage = topicImage;
        this.latter = latter;
    }

    public Boolean getSaved() {
        return saved;
    }

    public void setSaved(Boolean saved) {
        this.saved = saved;
    }

    public String getTopicId() {
        return topicId;
    }

    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public String getTopicImage() {
        return topicImage;
    }

    public void setTopicImage(String topicImage) {
        this.topicImage = topicImage;
    }

    public String getLatter() {
        return latter;
    }

    public void setLatter(String latter) {
        this.latter = latter;
    }

}
